### ISSUE TITLE
请求收入OpenWHU项目

### ISSUE THREAD

**Issue by Crescentm** [SmallZhezhe/ComplierTasks#1]
想把学长您的实验资料收集进OpenWHU项目，望批准❤
[项目地址](https://github.com/openwhu/OpenWHU)

**Comment by yunzhe99** [comment]
欢迎！这个项目很棒，期待你们的成功！

**Comment by Crescentm** [comment]
https://github.com/openwhu/OpenWHU/tree/master/%E4%B8%93%E4%B8%9A%E8%AF%BE/%E5%BC%98%E6%AF%85%E5%AD%A6%E5%A0%82/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/%E8%AF%BE%E7%A8%8B%E8%AE%BE%E8%AE%A1%E5%AE%9E%E9%AA%8C
谢谢学长的支持
